version: 0.2

phases:
  install:
    commands:
      - echo running Gulp Install..
      - sudo npm install gulp-cli -g 
      - sudo npm install gulp -D
  pre_build:
    commands:
      - echo Installing NPM dependencies...
      - sudo npm install  --save-dev   
  build:
    commands:
      -  echo Build started on `date`      
      -  gulp run 
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files: 
    - '**/*'
  base-directory: 'build'
  
    